### ISSUE TITLE
I think number of recipes required to make an item is a more useful concept than cost

### ISSUE THREAD

**Issue by acornmonkey** [expitau/InfiniteCraftWiki#16]
Cost doesn't really have much of an impact if you ask me. As when you make an item, you can easily duplicate it. So requiring duplication doesn't really make it much harder to make the item, even if the item being duplicated has a high cost.

This is similar to the concept of ranks.
https://infinite-craft-nealfun.fandom.com/wiki/Ranks

However, I think number of recipes required is a better concept than ranks too. I don't see any point in adding one to the number of recipes required to make the rank number.

**Comment by expitau** [comment]
Thanks for the feedback! I agree, I think that some work could be done on the algorithm here to rank costs of items. However, I made this tradeoff because there are quite a few items that need to be processed, and the current algorithm is a "good enough" heuristic. I'll take a look and see if there's anything that can be done to improve it.
