### ISSUE TITLE
Issue about loaded crafts from Infinite Craft game

### ISSUE THREAD

**Issue by SayanelFillaim** [expitau/InfiniteCraftWiki#9]
I have discovered crafts that aren't on your website. When I load my game, it don't show the items i have but you don't have.
You should add new recipes and items depending on what are on the game when we load. In that case, it will help to get everything from the game.

For example, I have "Type" That you don't have. 
You can view here how to obtain it : https://ics.vantezzen.io/Type (600 recipes needed to optain it)
I tried to look for Pokemon Type, that's why I researched Type in first place, then I look up on some website to see what we can do with "Type" and... that's the moment I realised no website got it. Not even the ingredients needed for. 
So I Hope it will help to add some new recipes and stuff. 

Maybe using an IA to test every recipe to look at what we get could help to get everything on the website !

**Comment by acornmonkey** [comment]
If this was implemented, it would make vandalising Infinite Craft Wiki really easy. It would be a headache to clean up. The script would have no way of knowing that the player hasn't made up elements.

Also, no recipes could be added, because Infinite Craft does not keep track of them in your browser. If the script could add recipes and did so, the problem would be even worse though. Because at least elements with no recipes to make them are suspicious, and can be easily removed with a script.

But perhaps it wouldn't hurt for the script to give you the option to open a pull request for the elements you have but Infinite Craft Wiki doesn't.

**Comment by reumarks** [comment]
Yeah, it would be pretty interesting to see if there was a clean way to let people contribute to the database themselves to add the recipes that they have found and want to share.

I agree that submitting recipes directly is probably a bad idea, but it might be feasible to setup a page where users could submit two existing elements to the server, and the server would check their crafting result with Infinite Craft directly to add their result to the main database.

You would only be able to craft one element at a time, and so it would be a bit annoying to use if you are trying to add something that is down a long rabbit hole, but that seems like it might work alright.

The main issue that I see is that in order to update the list of elements and recipes on the fly, we would need to move all of the chunk data off of GitHub and onto a personal server, which might have some downsides, but it's possible.

I don't think this is a priority quiet yet since there are other things that are currently under development, but I'll keep it in the back of my mind, and this might be something that is added down the line.

**Comment by Jcw87** [comment]
> For example, I have "Type" That you don't have. You can view here how to obtain it : https://ics.vantezzen.io/Type (600 recipes needed to optain it)

I found a much more efficient path to "Type" that only requires 15 recipes
![image](https://github.com/expitau/InfiniteCraftWiki/assets/975426/a59bd5f8-1501-4972-a272-cf8a05600ccd)
